version: '2'
services:
  # zookeeper:
  #   image: confluentinc/cp-zookeeper:latest
  #   environment:
  #     ZOOKEEPER_CLIENT_PORT: 2181
  #     ZOOKEEPER_TICK_TIME: 2000
  #   ports:
  #     - 22181:2181
  
  # kafka:
  #   image: confluentinc/cp-kafka:latest
  #   depends_on:
  #     - zookeeper
  #   ports:
  #     - 29092:29092
  #   environment:
  #     KAFKA_BROKER_ID: 1
  #     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  #     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
  #     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
  #     KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
  #     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  authserver:
    image: docker-ws-server:latest
    ports:
      - 9000:8080

  db:
    image: postgres:14.3
    restart: always
    ports:
      - 9002:5432
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
    environment:
      POSTGRES_USER: jlemein
      POSTGRES_PASSWORD: admin

  pgadmin:
    image: dpage/pgadmin4:6.9
    ports:
      - 9003:80
    environment:
      PGADMIN_DEFAULT_EMAIL: jeffrey.lemein@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin

  adminer:
    image: adminer
    ports:
      - 9004:8080
    environment:
      ADMINER_DEFAULT_SERVER: db

